---
title: "exploratory_plots"
author: "Stijn Van Hoey"
date: "September 30, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
library(dplyr)
library(ggplot2)

dataH <- "data/interim/dataH_enriched.csv"
dataH <- read.csv(dataH, header = TRUE, stringsAsFactors = FALSE)
```

## Plot number of eel per location

```{r pressure, echo=FALSE}
detections <- dataH %>% group_by(Station.Name, Transmitter) %>%
                            count() %>% 
                            group_by(Station.Name) %>% 
                            count()
ggplot(detections, aes(x = Station.Name, y = nn)) + 
    geom_bar(stat = "identity") + 
    ylab("Number of eel per location")

```

## Plot number of locations per eel

```{r}
detections <- dataH %>% group_by(Station.Name, Transmitter) %>%
                            count() %>% 
                            group_by(Transmitter) %>% 
                            count()
ggplot(detections, aes(x = Transmitter, y = nn)) + 
    geom_bar(stat = "identity") + 
    ylab("Number of locations per eel") +
    coord_flip()
```

## Plot number of moves

```{r}
detections = dataH %>% group_by(Transmitter) %>%
                          select(Transmitter)

detections$moves="1"
detections$moves=as.numeric(detections$moves)


summary=summarise(detections,
                  eels=n_distinct(Transmitter),
                  moves=n()
)

summary$eels=NULL
summary$moves=as.numeric(summary$moves)
par(mar=c(6,4.1,4.1,2.1))
barplot(summary$moves, names.arg=summary$Transmitter, cex.names=0.8, ylim=c(0,2000),las=2)
```

## Plot total number of detections per eel 

```{r}
detections = dataH %>%
  group_by(Transmitter)%>%
  select(Transmitter, Detections)%>%
  summarize(maxdetections = sum(Detections))

detections$maxdetections=as.numeric(detections$maxdetections)
par(mar=c(6,4.1,4.1,2.1))
barplot(detections$maxdetections, names.arg=detections$Transmitter, cex.names=0.8, ylim=c(0,350000), las=2)
```





